

export const ActionTypes = {
    LIST_OF_DEVICES : "LIST_OF_DEVICES",
    SELECTED_DEVICEID: "SELECTED_DEVICEID",
    SELECTED_DEVICE_INFO : "SELECTED_DEVICE_INFO",
    SELECTED_DEVICE_LATITUDE : "SELECTED_DEVICE_LATITUDE",
    SELECTED_DEVICE_LONGITUDE : "SELECTED_DEVICE_LONGITUDE",
    LOGGED_IN_USER: "LOGGED_IN_USER",
    ORDER_DETAILS : "ORDER_DETAILS",
    CONTINUOUS_SIGNIN_TIMER_START : "CONTINUOUS_SIGNIN_TIMER_START",
    CONTINUOUS_SIGNIN_TIMER_STOP : "CONTINUOUS_SIGNIN_TIMER_STOP",
    TRACKING_PERIOD_NORMAL : "TRACKING_PERIOD_NORMAL",
    TRACKING_PERIOD_POWERSAVING : "TRACKING_PERIOD_POWERSAVING",
    TRACKING_PERIOD_TRACKING : "TRACKING_PERIOD_TRACKING",
  };