

export const ActionTypes = {
    SELECTED_DEVICEID: "SELECTED_DEVICEID",
    LOGGED_IN_USER: "LOGGED_IN_USER",
    ORDER_DETAILS : "ORDER_DETAILS",
    CONTINUOUS_SIGNIN_TIMER_START : "CONTINUOUS_SIGNIN_TIMER_START",
    CONTINUOUS_SIGNIN_TIMER_STOP : "CONTINUOUS_SIGNIN_TIMER_STOP",
    TRACKING_PERIOD : "TRACKING_PERIOD",
  };